[package]
name = "zkp-dsa-r1cs"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.3"
ark-ec = "0.3"
ark-std = "0.3"
ark-bls12-381 = "0.3"
ark-groth16 = "0.3"
ark-marlin = "0.3"
ark-poly = "0.3"
ark-relations = "0.3"
ark-serialize = "0.3"
ark-snark = "0.3"
rand = "0.8"
